In [2]:
import pandas as pd
import geopandas as gp
import numpy as np
import folium

## Pull out the suppresed trips and assign them to census tracts

* Trips are suppressed to community areas when there is less than 3 trips for OD-15min 
* Assign those trips randomly to the census tracts within the community area that the suppressed trip is assigned to

In [3]:
tods = [1,2,3,4,5]
years = [2018,2019,2020]

In [4]:
agg = {'SCALED_SUP_PRIVATE_TRIPS':'sum', 'SCALED_SUP_SHARED_TRIPS':'sum', 'Pickup Community Area':'first', 'Dropoff Community Area':'first'}

In [5]:
df= pd.DataFrame()

In [ ]:
#df = pd.read_hdf('C:/Workspace/TNC-Demand-Model/Inputs/Chicago Ride-Hailing/Chicago_TNC_Trips_20.H5', where = ['YEAR == 2019'], key = 'Weekday_' + str(1))

In [19]:
df = store.select(where = ['YEAR == 2020'], key = 'Weekday_' + str(5))

In [20]:
df[df['MONTH'] == 3]

,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,...,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,YEAR,MONTH,DOW,HOUR
72643,8cd3fe1eb35b48d6d9006195989105031f0b0e08,2020-03-05 19:45:00,2020-03-05 20:30:00,2725.0,12.7,NaN,1.703108e+10,NaN,8.0,20.0,...,NaN,NaN,NaN,41.900221,-87.629105,POINT (-87.6291051864 41.9002212967),2020,3,3,19
74142,8cd43a436d764c6ef02b7eadd741bed60a65ab95,2020-03-27 20:00:00,2020-03-27 20:00:00,220.0,1.2,NaN,NaN,10.0,10.0,2.5,...,41.985015,-87.804532,POINT (-87.8045320063 41.9850151008),41.985015,-87.804532,POINT (-87.8045320063 41.9850151008),2020,3,4,20
136421,8cd9c15f93db98c2217ba25f4138ac2c49899784,2020-03-24 19:45:00,2020-03-24 20:00:00,684.0,3.2,NaN,NaN,23.0,29.0,7.5,...,41.900070,-87.720918,POINT (-87.7209182385 41.9000696026),41.860190,-87.717220,POINT (-87.7172201 41.8601900192),2020,3,1,19
282248,8cebdf560fdc13e7936c9b4cbc6c124551ec5bb4,2020-03-30 20:30:00,2020-03-30 21:00:00,1621.0,17.8,1.703161e+10,NaN,61.0,NaN,25.0,...,41.816178,-87.675102,POINT (-87.6751020589 41.8161780153),NaN,NaN,NaN,2020,3,0,20
284245,8cebf4f062917c20ed3e547b55d70bd287140ed5,2020-03-02 20:45:00,2020-03-02 20:45:00,346.0,1.2,NaN,NaN,29.0,26.0,7.5,...,41.860190,-87.717220,POINT (-87.7172201 41.8601900192),41.878594,-87.730232,POINT (-87.7302324284 41.8785943576),2020,3,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152400780,8cbba1ae6906462db1108555997fd4c133e8a3e3,2020-03-30 21:00:00,2020-03-30 21:00:00,637.0,3.2,NaN,NaN,NaN,25.0,5.0,...,NaN,NaN,NaN,41.890609,-87.756047,POINT (-87.7560467111 41.8906088526),2020,3,0,21
152407691,8cbcb93fcdf91984c4abef1054fbd68b39464365,2020-03-20 21:15:00,2020-03-20 21:45:00,1599.0,18.0,NaN,NaN,76.0,NaN,25.0,...,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,2020,3,4,21
152422074,8cbe30f144b285a6be1161e60a9243e2a9b6eddf,2020-03-26 21:00:00,2020-03-26 21:15:00,829.0,4.3,NaN,NaN,27.0,23.0,10.0,...,41.878914,-87.705897,POINT (-87.7058971305 41.8789144956),41.900070,-87.720918,POINT (-87.7209182385 41.9000696026),2020,3,3,21
152450466,8cb4a5c767ab681044fd1d9c8c4ce38cab9d5b22,2020-03-10 20:00:00,2020-03-10 20:30:00,1930.0,19.2,1.703135e+10,NaN,35.0,NaN,27.5,...,41.827789,-87.614187,POINT (-87.6141870291 41.8277887624),NaN,NaN,NaN,2020,3,1,20
152488685,8cc897c7ce1d75aec7dcbc1b30a0bb45065723c0,2020-03-31 19:15:00,2020-03-31 19:15:00,665.0,1.8,NaN,NaN,56.0,56.0,7.5,...,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),2020,3,1,19

In [14]:
conflation = pd.read_csv('C:/Workspace/TNC-Demand-Model/Inputs/Chicago Community Areas/Community_Area_to_Census_Tract.csv')
conflation['COMMUNITY_AREA'] = conflation.area_num_1.astype(float)
store = pd.HDFStore('C:/Workspace/TNC-Demand-Model/Inputs/Chicago Ride-Hailing/Chicago_TNC_Trips_20.H5')

for year in years:  
    if year == 2018:
        months = [11,12]
    elif year == 2020:
        months = [1,2]
    else:
        months = [1,2,3,4,5,6,7,8,9,10,11,12]
        
    print('Working on year ' + str(year))
    df5 = pd.DataFrame()
    
    for month in months:
        print('Working on month ' + str(month))
        df4 = pd.DataFrame()
        
        for tod in tods:
            print('Working on tod ' + str(tod))

            df3 = pd.DataFrame()
            df2 = pd.DataFrame()
            df = pd.DataFrame()
            df = pd.read_hdf('C:/Workspace/TNC-Demand-Model/Inputs/Chicago Ride-Hailing/Chicago_TNC_Trips_20.H5', where = 'YEAR == ' + str(year), key = 'Weekday_' + str(tod))

            print('Filtering the Data!')
            df = df[df['MONTH']== year]
            df['DAY'] = df['Trip Start Timestamp'].dt.day

            print(str(len(df[(~np.isnan(df['Pickup Community Area']))&(np.isnan(df['Pickup Census Tract']))&(~np.isnan(df['Dropoff Community Area'])) & (np.isnan(df['Dropoff Census Tract']))])) +  ' Trip Records with Suppressed Origin and Destination out of ' + str(len(df)) )
            print(str(len(df[((np.isnan(df['Pickup Community Area']))&(~np.isnan(df['Pickup Census Tract'])))|((np.isnan(df['Dropoff Community Area'])) & (np.isnan(df['Dropoff Census Tract'])))])) +  ' Trip Records Outside of Chicago but within cook county out of ' + str(len(df)) )
            print(str(len(df[((~np.isnan(df['Pickup Community Area']))&(~np.isnan(df['Pickup Census Tract'])))&((~np.isnan(df['Dropoff Community Area'])) & (~np.isnan(df['Dropoff Census Tract'])))])) +  ' Trip Records with both trip ends within Chicago out of ' + str(len(df)) )
            print(str(len(df[(np.isnan(df['Pickup Community Area']))|(np.isnan(df['Dropoff Community Area']))])) +  ' Trip Records with one trip end outside of Cook county out of ' + str(len(df)) )


            #select out the trips that have community area data and are missing census tract data 
            df['SUP_PRIVATE_TRIPS'] = np.where(df['Shared Trip Authorized'] == False, 1, 0)
            df['SUP_SHARED_TRIPS'] = np.where(df['Shared Trip Authorized'] == True, 1, 0)
            df = df[(np.isnan(df['Pickup Census Tract']))|(np.isnan(df['Dropoff Census Tract']))]
            df = df[~np.isnan(df['Pickup Community Area'])&(~np.isnan(df['Dropoff Community Area']))]


            df = df.groupby(by = ['Pickup Community Area', 'Dropoff Community Area', 'YEAR','MONTH','DAY'], as_index = False).sum()
            df = df.groupby(by = ['Pickup Community Area', 'Dropoff Community Area','YEAR','MONTH'], as_index = False).mean()

            print('There are ' +str(df.SUP_PRIVATE_TRIPS.sum() + df.SUP_SHARED_TRIPS.sum()) + ' Average Weekday Trips that are Suppressed!')

            #make a column to iterate through
            df['OD_PAIRS'] = df['Pickup Community Area'].astype(str) + '_' + df['Dropoff Community Area'].astype(str)

            #iterate through each of the suppressed Community Areas
            print('Working on assigning suppressed trips!')
            for od in df['OD_PAIRS'].unique():

                #select out the trips that are originating from the given community area
                od_trips = df[df['OD_PAIRS'] == od]

                #conflate the community area to the census tract centroids that fall within it
                df2 = od_trips[['SUP_PRIVATE_TRIPS', 'SUP_SHARED_TRIPS', 'Pickup Community Area', 'Dropoff Community Area']].merge(conflation[['GEOID','COMMUNITY_AREA']], how = 'left', left_on = 'Pickup Community Area' , right_on = 'COMMUNITY_AREA')
                df2 = df2.merge(conflation[['GEOID','area_num_1']], how = 'left', left_on = 'Dropoff Community Area' , right_on = 'area_num_1', suffixes = ('_PICKUP','_DROPOFF'))

                df2['SCALAR'] = np.random.dirichlet(np.ones(len(df2)))
                df2['SCALED_SUP_PRIVATE_TRIPS'] = df2['SUP_PRIVATE_TRIPS']*df2['SCALAR']
                df2['SCALED_SUP_SHARED_TRIPS'] = df2['SUP_SHARED_TRIPS']*df2['SCALAR']
                df3 = df3.append(df2)
            df3['TOD'] = tod       
            
            df4 = df3.append(df3)
        df4['MONTH'] = month
        print(str(df4.SCALED_SUP_PRIVATE_TRIPS.sum()))
        print(str(df4.SCALED_SUP_SHARED_TRIPS.sum()))
        
        df5 = df4.append(df4)
    df5['YEAR'] = year    
       
    df6 = df5.append(df5)
    

grouped = df6[['SCALED_SUP_PRIVATE_TRIPS','SCALED_SUP_SHARED_TRIPS', 'GEOID_PICKUP','GEOID_DROPOFF', 'MONTH','YEAR','Pickup Community Area', 'Dropoff Community Area']].groupby(by = ['GEOID_PICKUP', 'GEOID_DROPOFF','MONTH','YEAR'], as_index = False).agg(agg)        




print('Everyting is Complete!')

Working on year 2018
Working on month 11
Working on tod 1
Filtering the Data!
289820 Trip Records with Suppressed Origin and Destination out of 952035
72940 Trip Records Outside of Chicago but within cook county out of 952035
525826 Trip Records with both trip ends within Chicago out of 952035
136389 Trip Records with one trip end outside of Cook county out of 952035
There are 16007.083984505345 Average Weekday Trips that are Suppressed!
Working on assigning suppressed trips!
Working on tod 2
Filtering the Data!
172211 Trip Records with Suppressed Origin and Destination out of 838357
48713 Trip Records Outside of Chicago but within cook county out of 838357
560565 Trip Records with both trip ends within Chicago out of 838357
105581 Trip Records with one trip end outside of Cook county out of 838357
There are 10565.068781193007 Average Weekday Trips that are Suppressed!
Working on assigning suppressed trips!
Working on tod 3
Filtering the Data!
431977 Trip Records with Suppressed Origin and Destination out of 1920351
140620 Trip Records Outside of Chicago but within cook county out of 1920351
1209303 Trip Records with both trip ends within Chicago out of 1920351
279071 Trip Records with one trip end outside of Cook county out of 1920351
There are 22350.420361492652 Average Weekday Trips that are Suppressed!
Working on assigning suppressed trips!
Working on tod 4
Filtering the Data!
173384 Trip Records with Suppressed Origin and Destination out of 1219367
69532 Trip Records Outside of Chicago but within cook county out of 1219367
907473 Trip Records with both trip ends within Chicago out of 1219367
138510 Trip Records with one trip end outside of Cook county out of 1219367
There are 10891.732273806345 Average Weekday Trips that are Suppressed!
Working on assigning suppressed trips!
Working on tod 5
Filtering the Data!
0 Trip Records with Suppressed Origin and Destination out of 0
0 Trip Records Outside of Chicago but within cook county out of 0
0 Trip Records with both trip ends within Chicago out of 0
0 Trip Records with one trip end outside of Cook county out of 0
There are 0 Average Weekday Trips that are Suppressed!
Working on assigning suppressed trips!

AttributeError: 'DataFrame' object has no attribute 'SCALED_SUP_PRIVATE_TRIPS'

## Total Number of Suppressed Trips

In [ ]:
df_all.SCALED_SUP_PRIVATE_TRIPS.sum() + df_all.SCALED_SUP_SHARED_TRIPS.sum()

## Aggregate the data to an average weekday by TOD

In [12]:
grouped.to_csv('C:/Workspace/TNC-Demand-Model/Inputs/Chicago Ride-Hailing/Monthly Suppressed Trips.csv')

## Visualize the Suppressed Trips

In [13]:
grouped['TOTAL_SUP_TRIPS'] = grouped.SCALED_SUP_PRIVATE_TRIPS + grouped.SCALED_SUP_SHARED_TRIPS

In [14]:
origin = grouped[['GEOID_PICKUP', 'TOTAL_SUP_TRIPS']].groupby(by = 'GEOID_PICKUP', as_index = False).sum()
dest = grouped[['GEOID_DROPOFF', 'TOTAL_SUP_TRIPS']].groupby(by = 'GEOID_DROPOFF', as_index = False).sum()

In [15]:
geo = gp.read_file('C:/Workspace/TNC-Demand-Model/Inputs/Census Shapefiles/Chicago Tracts/geo_export_558aad9f-98d8-4dd5-a6b1-c1730155d596.shp')

In [16]:
origin[origin['GEOID_PICKUP'] == 17031081403]

     GEOID_PICKUP  TOTAL_SUP_TRIPS
137   17031081403       116.343629

In [17]:
origin['GEOID_PICKUP'] = origin.GEOID_PICKUP.astype(float)
dest['GEOID_DROPOFF'] = dest.GEOID_DROPOFF.astype(float)

In [18]:
geo['geoid10'] = geo.geoid10.astype(float)

In [19]:
centroids = pd.read_csv('C:/Workspace/TNC-Demand-Model/otp/points.csv')
centroids = gp.GeoDataFrame(centroids)

In [20]:
geo[geo['geoid10'] == 17031081403]

,commarea,commarea_n,countyfp10,geoid10,name10,namelsad10,notes,statefp10,tractce10,geometry
165,8,8.0,031,1.703108e+10,814.03,Census Tract 814.03,Small unpopulated area in CA 32,17,081403,"POLYGON ((-87.60953 41.89096, -87.60484 41.891..."

In [21]:
m = folium.Map([41.8781, -87.6298], zoom_start=11)
    
    
# Add the color for the chloropleth:
folium.Choropleth(
 geo_data=geo,
 name= "Suppressed Pickups",
 data=origin,
 columns = ['GEOID_PICKUP', 'TOTAL_SUP_TRIPS'],
 key_on='feature.properties.geoid10',
 fill_color='BuGn',
 fill_opacity=0.6,
 line_opacity=0.2,
 legend_name='Average Weekday Pickups',
 highlight = True
).add_to(m)

folium.Choropleth(
 geo_data=geo,
 name= "Suppressed Dropoffs",
 data=dest,
 columns = ['GEOID_DROPOFF', 'TOTAL_SUP_TRIPS'],
 key_on='feature.properties.geoid10',
 fill_color='BuGn',
 fill_opacity=0.6,
 line_opacity=0.2,
 legend_name='Average Weekday Dropoffs',
 highlight = True
).add_to(m)

feature_group = folium.FeatureGroup(name='Census Tract Centroids', show = False)


for tract2 in centroids.GEOID:
    row = centroids[centroids['GEOID'] == tract2]
    folium.CircleMarker([row['Y'], row['X']], popup = str(int(row['GEOID'].values[0])), radius = 1, fill = True, fill_color = 'grey', color = 'grey').add_to(feature_group)

m.add_child(feature_group)


folium.LayerControl().add_to(m)

m.save('C:/Workspace/TNC-Demand-Model/Data Exploration/Suppressed Ridehailing Maps/Suppressed_Trips.html')

print('Everything is Complete!')

Everything is Complete!